[bindings]
name = "teammate"
teammate.udl = "src/uniffi-bindgen.rs"
udl_file = "src/teammate.udl"

[bindings.python]
format_code = false

[custom-types]
Ulid = { module = "crate::models::custom_ulid" }
